//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaVenti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string id_book { get; set; }
        public string fk_id_category { get; set; }
        public string fk_id_promo { get; set; }
        public string name_book { get; set; }
        public string author { get; set; }
        public decimal price_book { get; set; }
        public int pages { get; set; }
        public System.DateTime date_published { get; set; }
        public string publisher { get; set; }
        public int stock { get; set; }
    }
}
