//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaVenti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id_emp { get; set; }
        public string email_emp { get; set; }
        public string password_emp { get; set; }
        public string name_emp { get; set; }
        public string gender { get; set; }
        public string phone_num_emp { get; set; }
        public string role { get; set; }
    }
}
