//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaVenti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string id_payment { get; set; }
        public string fk_id_order { get; set; }
        public decimal subtotal { get; set; }
        public decimal total_payment { get; set; }
    }
}
