//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaVenti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo
    {
        public string id_promo { get; set; }
        public string name_promo { get; set; }
        public double discount { get; set; }
        public System.DateTime start_discount { get; set; }
        public System.DateTime end_discount { get; set; }
    }
}
